import type { ANSIKind } from "../../../../styling/types";
import BaseToken from "../assets/__base.token__";

/**
 * ANSI escape sequence token used for terminal styling and formatting.
 *
 * `AnsiToken` represents a low-level terminal control instruction
 * inserted during the rendering phase to apply visual styling such as:
 *
 * - foreground colors
 * - background colors
 * - text modifiers
 * - formatting resets
 *
 * ---------------------------------------------------------------------
 * 🔷 ARCHITECTURAL ROLE
 * ---------------------------------------------------------------------
 *
 * `AnsiToken` belongs exclusively to the **rendering phase**
 * of the rendering pipeline.
 *
 * Unlike semantic tokens produced during tokenization,
 * ANSI tokens are presentation-layer artifacts generated by renderers
 * after semantic tokenization has already completed.
 *
 * Rendering pipeline overview:
 *
 * ```text
 * JavaScript Value
 *        ↓
 * Graphing
 *        ↓
 * GraphNode tree
 *        ↓
 * Representation
 *        ↓
 * RepresentationNode tree
 *        ↓
 * Tokenization
 *        ↓
 * Semantic Token Stream
 *        ↓
 * Rendering
 *        ↓
 * RenderingBuffer
 *        ↓
 * Serialization
 *        ↓
 * Final string output
 * ```
 *
 * `AnsiToken` is injected during the:
 *
 * ```text
 * Rendering → RenderingBuffer
 * ```
 *
 * stage.
 *
 * ---------------------------------------------------------------------
 * 🔷 DESIGN INTENT
 * ---------------------------------------------------------------------
 *
 * This token exists to:
 *
 * - represent terminal styling instructions structurally
 * - decouple styling logic from raw string concatenation
 * - allow renderer-controlled theming
 * - support terminal-aware rendering behavior
 * - preserve separation between semantics and presentation
 *
 * ---------------------------------------------------------------------
 * 🔷 SEMANTIC SEPARATION
 * ---------------------------------------------------------------------
 *
 * `AnsiToken` is intentionally NOT part of:
 *
 * - graphing
 * - representation
 * - semantic tokenization
 *
 * because ANSI styling is not semantic data.
 *
 * It is purely a rendering concern.
 *
 * This separation allows:
 *
 * - renderer-independent tokenization
 * - multiple rendering targets
 * - theming abstraction
 * - non-terminal renderers to ignore ANSI entirely
 *
 * ---------------------------------------------------------------------
 * 🔷 TYPE SAFETY & INVARIANTS
 * ---------------------------------------------------------------------
 *
 * The constructor enforces a strict invariant:
 *
 * - If the ANSI code is `\x1b[0m` (reset sequence),
 *   then the `type` MUST be `'reset'`.
 *
 * This guarantees semantic consistency for reset operations.
 *
 * ---------------------------------------------------------------------
 * 🔷 RENDERING BEHAVIOR
 * ---------------------------------------------------------------------
 *
 * `AnsiToken` participates only in rendering and serialization.
 *
 * It:
 * - contributes no visible semantic content
 * - contributes zero logical width
 * - should not affect wrapping calculations
 * - should not affect layout grouping
 *
 * Renderers are responsible for:
 * - injecting ANSI tokens
 * - balancing reset sequences
 * - managing nested styles
 *
 * ---------------------------------------------------------------------
 * 🔷 IMMUTABILITY MODEL
 * ---------------------------------------------------------------------
 *
 * Both the ANSI code and semantic type are immutable after construction.
 *
 * This guarantees stable rendering behavior during streaming output.
 *
 * ---------------------------------------------------------------------
 * @since 1.0.0
 */
export class AnsiToken extends BaseToken<'ansi'> {
    /**
     * Raw ANSI escape sequence string used for terminal styling.
     *
     * Example:
     * - `\x1b[31m` → red text
     * - `\x1b[0m`  → reset formatting
     *
     * @since 1.0.0
     */
    readonly #_code: string;

    /**
     * Semantic classification of the ANSI sequence.
     *
     * This allows renderers to reason about styling intent
     * without parsing escape codes directly.
     *
     * Example values:
     * - `color`
     * - `bg`
     * - `style`
     * - `reset`
     *
     * @since 1.0.0
     */
    readonly #_type: ANSIKind;

    /**
     * Creates a new ANSI formatting token.
     *
     * @param code - Raw ANSI escape sequence
     * @param type - Semantic classification of the ANSI sequence
     *
     * @throws Error if `code === '\x1b[0m'` and `type !== 'reset'`
     *
     * @since 1.0.0
     */
    constructor(code: string, type: ANSIKind) {
        super('ansi');

        if (code === '\x1b[0m' && type !== 'reset') {
            throw new Error(`Invariant violation: type must be 'reset' when code is '\x1b[0m'`);
        }

        if (code === '\x1b[0m') {
            this.#_type = 'reset';
        } else {
            this.#_type = type;
        }

        this.#_code = code;
    }

    /**
     * Returns the raw ANSI escape sequence.
     *
     * This value is written directly into terminal output streams
     * by the renderer.
     *
     * @returns ANSI escape sequence string
     *
     * @since 1.0.0
     */
    get code(): string {
        return this.#_code;
    }

    /**
     * Returns the semantic ANSI classification.
     *
     * This metadata allows renderers and debugging utilities
     * to reason about styling behavior symbolically rather than
     * parsing raw escape codes.
     *
     * @returns ANSI semantic type
     *
     * @since 1.0.0
     */
    get type(): ANSIKind {
        return this.#_type;
    }
}