import atomix from "@nasriya/atomix";
import interceptors from "./interceptors";
import ZexiTerminalControllerInstance from "../controller/controller";
import queryCursorPosition from "./helpers/cursor.position";
import { Console } from 'node:console';
import type { CursorPosition, ProcessStdWriteStream, TerminalBufferEntry, TerminalOriginals, WriteReturnType, } from "./types";

/**
 * Provides the low-level terminal I/O interface used by Zexi.
 *
 * This class owns physical writes to the configured standard streams and
 * terminal control operations. It captures the original stream operations
 * before installing Zexi's interceptors and retains their original function
 * references as the direct physical I/O path used by Zexi.
 *
 * Terminal control operations are implemented by Zexi and ultimately write
 * their control sequences through the captured original stream writers.
 * This allows Zexi to provide terminal-control operations independently of
 * whether the underlying streams natively expose corresponding terminal
 * methods.
 *
 * This class is the low-level I/O boundary used by the terminal subsystem.
 * It is not intended to be called directly by consumers of the terminal
 * subsystem.
 *
 * ---------------------------------------------------------------------
 * 🔷 ORIGINAL STREAM OPERATIONS
 * ---------------------------------------------------------------------
 *
 * The configured standard-stream operations, together with the global
 * `console` instance, are captured before Zexi installs its interceptors.
 *
 * Available stream operations are captured as their original function
 * references without binding or otherwise modifying them. When invoked by
 * Zexi, the captured operations are called with their corresponding stream
 * as their `this` context so they retain the behavior of the original
 * stream methods.
 *
 * Stream operations that are unavailable in the current environment are
 * retained as `undefined`. Their absence does not prevent Zexi from
 * providing its own terminal-control operations.
 *
 * The captured stream writers provide the direct physical I/O path used by
 * Zexi. Terminal-control operations generate their corresponding ANSI
 * control sequences and write them through the captured original writers.
 *
 * These physical operations bypass the installed Zexi interceptors. This
 * prevents terminal operations performed internally by Zexi from re-entering
 * the interception pipeline.
 *
 * ---------------------------------------------------------------------
 * 🔷 INTERCEPTION
 * ---------------------------------------------------------------------
 *
 * Interception is controlled through the {@link intercepting} property.
 *
 * When interception is enabled:
 *
 * - stdout writes are handled by Zexi
 * - stderr writes are handled by Zexi
 * - terminal control operations generated by Zexi are written directly
 *   through the captured original stream writers
 *
 * When interception is disabled, the installed stream interceptors
 * transparently forward application output to the captured original stream
 * operations.
 *
 * Disabling interception does not remove the installed interceptors.
 *
 * ---------------------------------------------------------------------
 * 🔷 INSTALLATION
 * ---------------------------------------------------------------------
 *
 * Before installation, the original standard-stream operations and global
 * console instance must have been captured.
 *
 * Installation replaces the configured standard-stream operations supported
 * by Zexi with its interceptors and replaces the global `console` with a
 * Zexi-controlled `Console` instance.
 *
 * Zexi may provide terminal-control operations even when the corresponding
 * operations were not originally available on the configured streams. Such
 * operations are removed or restored to their captured original values when
 * the interceptors are uninstalled.
 *
 * The interceptors are installed at most once for the current stream
 * configuration and remain installed until {@link uninstall} is called.
 *
 * The {@link installed} property indicates whether the configured standard
 * streams currently contain Zexi's interceptors.
 *
 * Installation and interception are therefore separate states:
 *
 * - installed + intercepting: Zexi is actively intercepting terminal I/O
 * - installed + not intercepting: Zexi's interceptors are installed but
 *   transparently forwarding operations
 * - not installed + not intercepting: the configured streams are untouched
 *
 * ---------------------------------------------------------------------
 * 🔷 STREAM CONFIGURATION
 * ---------------------------------------------------------------------
 *
 * The streams used by the terminal I/O interface are exposed through
 * {@link streams}. They normally reference `process.stdout` and
 * `process.stderr`, but may be replaced through {@link replaceStreams}.
 *
 * The stream references must not be replaced directly. {@link replaceStreams}
 * must be used when changing the configured streams so that the currently
 * captured original operations are discarded and recaptured from the new
 * streams before interception is restored.
 *
 * ---------------------------------------------------------------------
 * 🔷 SIGNAL HANDLING
 * ---------------------------------------------------------------------
 *
 * When interception is enabled, handlers for `SIGINT` and `SIGTERM` are
 * registered.
 *
 * Before terminating the process, these handlers wait for the Zexi terminal
 * controller queue to complete. This allows pending terminal operations to
 * finish before the process exits.
 *
 * The handlers are removed when interception is disabled.
 *
 * ---------------------------------------------------------------------
 * 🔷 UNINSTALLATION
 * ---------------------------------------------------------------------
 *
 * Calling {@link uninstall} removes Zexi's interceptors and restores the
 * captured original stream operations, including `undefined` for operations
 * that were not originally available.
 *
 * The global `console` is restored to the exact instance that existed before
 * Zexi installed its interceptors.
 *
 * Unlike disabling interception through {@link intercepting}, uninstallation
 * removes Zexi's modifications from the configured standard streams.
 *
 * ---------------------------------------------------------------------
 * 🔷 INTERNAL OUTPUT
 * ---------------------------------------------------------------------
 *
 * Zexi uses {@link write} for physical output that must bypass interception.
 *
 * The output stream is selected using the `isError` option:
 *
 * - `false` writes to stdout
 * - `true` writes to stderr
 *
 * Terminal control methods generate their control sequences and write them
 * through the captured original writer rather than through the intercepted
 * standard-stream methods.
 *
 * @since 1.0.0
 */
export class ZexiTerminalIO {
    /**
     * The standard streams currently managed by Zexi for terminal I/O.
     *
     * These streams represent the standard input and output streams used by Zexi's
     * terminal I/O system. They default to the process standard input, output,
     * and error streams of the environment in which ZexiTerminalIO is initialized.
     *
     * The streams must not be replaced directly. Use {@link replaceStreams} to
     * replace the managed streams, as it also invalidates the existing stream
     * bindings and captures the original operations of the new streams before
     * interception is resumed.
     *
     * Directly replacing any stream bypasses this rebinding lifecycle and may
     * leave the captured original operations associated with a different stream
     * configuration.
     *
     * @since 1.0.0
     */
    static readonly streams = {
        stdout: process.stdout,
        stderr: process.stderr,
        stdin: process.stdin
    };

    /**
     * Stores the original standard-stream operations and global console instance
     * captured from the currently configured terminal streams before Zexi installs
     * its interceptors.
     *
     * The original stream operations are captured by {@link #_bind} and bound to
     * their respective streams so they remain valid when invoked independently of
     * the streams' current methods.
     *
     * Stream operations that are unavailable on the original streams are omitted.
     * This allows Zexi to operate with non-TTY or otherwise limited streams while
     * retaining every physical terminal capability provided by the environment.
     *
     * The captured console instance is preserved so the global console can be
     * completely restored when the interceptors are uninstalled.
     *
     * @since 1.0.0
     */
    #_originals!: TerminalOriginals;

    /**
     * Tracks the binding, installation, readiness, and activation state of terminal
     * interception.
     *
     * `bound` indicates whether the original operations of the currently configured
     * terminal streams and the global console instance have been captured for direct
     * physical I/O and later restoration.
     *
     * `installed` indicates whether Zexi's interceptors are currently installed on
     * the configured terminal streams.
     *
     * `intercepting` indicates whether those installed interceptors are actively
     * processing terminal operations through Zexi.
     *
     * `ready` indicates whether terminal initialization has completed and queued
     * output may be flushed directly through the captured original stream operations.
     *
     * These states are intentionally independent because binding, installation,
     * interception, and readiness represent distinct stages of the terminal I/O
     * lifecycle. In particular, disabling interception leaves the interceptors
     * installed for transparent forwarding.
     *
     * The binding state applies to the current terminal-stream configuration and may
     * be reset when the configured streams are replaced.
     *
     * @since 1.0.0
     */
    readonly #_flags = Object.seal({
        intercepting: false,
        installed: false,
        ready: false,
        captured: false
    });

    /**
     * Manages installation, activation, and removal of terminal interception.
     *
     * This object owns the process-level modifications required for Zexi to
     * intercept standard-stream operations.
     *
     * Installation and activation are handled separately:
     *
     * - installation replaces the process stream methods with Zexi interceptors
     * - activation enables the interceptors to process operations through Zexi
     * - deactivation leaves the interceptors installed but makes them forward
     *   operations transparently
     * - uninstallation restores the original process stream methods
     *
     * The interception lifecycle also owns the signal handlers used to drain
     * pending terminal operations before process termination.
     *
     * @since 1.0.0
     */
    readonly #_interception = {
        /**
         * Stores the process termination handler registered while interception is
         * enabled.
         *
         * The handler waits for the terminal controller queue to complete before
         * terminating the process. This prevents pending terminal operations from
         * being abandoned during `SIGINT` or `SIGTERM`.
         *
         * The handler is removed when interception is disabled.
         *
         * @since 1.0.0
         */
        drainHandler: undefined as undefined | ((code: number) => Promise<void>),

        /**
         * Installs Zexi's terminal interceptors on the configured standard streams and
         * replaces the global console with a Zexi-controlled `Console` instance.
         *
         * Installation is idempotent. If the interceptors are already installed, no
         * changes are made.
         *
         * Original stream operations must have been captured before installation.
         * Attempting to install the interceptors before the originals have been captured
         * indicates an internal lifecycle violation and throws an `Error`.
         *
         * The installed interceptors replace the standard stream methods for:
         *
         * - stdout writes
         * - stderr writes
         * - cursor positioning
         * - relative cursor movement
         * - line clearing
         * - screen clearing
         *
         * After the stream interceptors are installed, a new `Console` instance is
         * created using the configured standard streams and assigned to
         * `globalThis.console`. Creating a new instance ensures that Zexi does not
         * depend on or modify the internal state of a previously created `Console`
         * instance and retains control over the global console output path.
         *
         * Installation does not enable active interception by itself.
         *
         * @throws {Error}
         * Thrown if the original standard-stream operations have not been captured
         * before installation.
         *
         * @since 1.0.0
         */
        install: () => {
            if (this.#_flags.installed) { return; }

            if (!this.#_flags.captured) {
                throw new Error(
                    'Invariant violation: Attempting to install terminal interceptors before the original stream operations have been captured.'
                );
            }

            const streams = ZexiTerminalIO.streams;
            streams.stdout.write = interceptors.stdoutWrite;
            streams.stderr.write = interceptors.stderrWrite;

            streams.stdout.cursorTo = streams.stderr.cursorTo = interceptors.cursorTo;
            streams.stdout.clearLine = streams.stderr.clearLine = interceptors.clearLine;
            streams.stdout.clearScreenDown = streams.stderr.clearScreenDown = interceptors.clearScreenDown;
            streams.stdout.moveCursor = streams.stderr.moveCursor = interceptors.moveCursor;

            globalThis.console = new Console({
                stdout: streams.stdout,
                stderr: streams.stderr,
            }) as any;

            this.#_flags.installed = true;
        },

        /**
         * Removes Zexi's terminal interceptors from the configured standard streams and
         * restores the original global console instance.
         *
         * If the interceptors are not installed, no changes are made.
         *
         * Each replaced stream method is restored to the original function reference
         * captured for that stream. The restored functions are not bound by Zexi;
         * they are assigned back to the configured streams and therefore retain the
         * stream as their `this` context when invoked normally.
         *
         * Stream methods that were unavailable when the originals were captured are
         * restored as `undefined`. The global `console` is restored to the exact
         * instance that existed before Zexi installed its interceptors.
         *
         * This operation only restores the installed terminal and console state.
         * Active interception and its signal handlers are managed separately by
         * {@link enable} and {@link disable}.
         *
         * @since 1.0.0
         */
        uninstall: () => {
            if (!this.#_flags.installed) { return; }
            const originals = this.#_originals;

            for (const _target of ['stdout', 'stderr'] as const) {
                const target = originals[_target];
                const streamTarget = ZexiTerminalIO.streams[_target];

                streamTarget.write = target.write!;
                streamTarget.cursorTo = target.cursorTo!;
                streamTarget.clearLine = target.clearLine!;
                streamTarget.clearScreenDown = target.clearScreenDown!;
                streamTarget.moveCursor = target.moveCursor!;
            }

            globalThis.console = originals.console;
            this.#_flags.installed = false;
        },

        /**
         * Enables active Zexi terminal interception.
         *
         * Enabling installs the terminal interceptors if they are not already
         * installed, registers the process signal handlers used to drain pending
         * Zexi work before termination, and marks the terminal as actively
         * intercepting application output.
         *
         * This operation is idempotent. If active interception is already enabled,
         * no changes are made.
         *
         * The process signal handlers are registered for:
         *
         * - `SIGINT`
         * - `SIGTERM`
         *
         * When either signal is received, pending Zexi terminal work is allowed to
         * complete before the process exits with the received termination code.
         *
         * Installation and active interception are separate states. Enabling
         * interception guarantees that the required terminal interceptors are
         * installed, but installing the interceptors alone does not enable active
         * interception.
         *
         * Original process stream operations must have been captured before
         * interception can be enabled. If the original operations have not been
         * captured, interceptor installation fails and active interception is not
         * enabled.
         *
         * @throws {Error}
         * Thrown if the original process stream operations have not been captured
         * before the terminal interceptors are installed.
         *
         * @since 1.0.0
         */
        enable: () => {
            const interception = this.#_interception;

            try {
                if (this.#_flags.intercepting) { return; }

                interception.drainHandler = atomix.utils.once(async (code: number) => {
                    const ct = ZexiTerminalControllerInstance;
                    await ct.queue.untilComplete();
                    process.exit(code);
                });

                process.on('SIGINT', interception.drainHandler);
                process.on('SIGTERM', interception.drainHandler);
            } finally {
                interception.install();
                this.#_flags.intercepting = true;
            }
        },

        /**
         * Disables active terminal interception.
         *
         * The installed interceptors are intentionally retained. While interception
         * is disabled, they transparently forward operations to the original
         * process stream methods.
         *
         * Any `SIGINT` and `SIGTERM` handlers registered by {@link enable} are
         * removed.
         *
         * Disabling interception does not restore the original process stream
         * methods. Use {@link uninstall} for that.
         *
         * @since 1.0.0
         */
        disable: () => {
            if (!this.#_flags.intercepting) { return; }

            this.#_flags.intercepting = false
            const drainHandler = this.#_interception.drainHandler;

            if (drainHandler) {
                process.removeListener('SIGINT', drainHandler);
                process.removeListener('SIGTERM', drainHandler);
            }
        }
    }

    /**
     * Stores intercepted terminal writes received before the terminal becomes
     * ready.
     *
     * Entries are retained in arrival order and flushed by `#_onReady` once
     * terminal initialization has completed.
     *
     * The buffer contains only requests received through the interception
     * pipeline. Direct writes performed through {@link write} bypass this buffer
     * and are written immediately to the original process streams.
     *
     * @since 1.0.0
     */
    readonly #_buffer: TerminalBufferEntry[] = [];

    /**
     * Completes the terminal readiness transition.
     *
     * Interception is enabled before the buffered requests are flushed so that
     * incoming writes continue to be captured while the buffer is being drained.
     *
     * Buffered requests are written directly to the original process streams in
     * their arrival order. The terminal is marked as ready only after the entire
     * buffer has been flushed so that writes received during the flush are also
     * retained and written in order.
     *
     * This handler can only execute once.
     *
     * @since 1.0.0
     */
    readonly #_onReady = atomix.utils.once(() => {
        this.#_interception.enable();

        while (this.#_buffer.length > 0) {
            const entry = this.#_buffer.shift()!;
            this.#_writeEntry(entry);
        }

        this.#_flags.ready = true;
    });

    /**
     * Writes a buffered terminal entry directly to its original process stream.
     *
     * The destination stream is selected from the entry's `isError` flag.
     * Encoding and completion callback arguments are forwarded according to the
     * standard Node.js `write()` overloads.
     *
     * This method bypasses Zexi's installed interceptors and is therefore safe to
     * use while flushing buffered requests.
     *
     * The selected original stream must provide a `write()` operation. Its absence
     * represents an internal terminal I/O invariant violation and causes an
     * {@link Error} to be thrown.
     *
     * @param entry - Buffered terminal write to flush.
     *
     * @returns The return value of the original standard-stream `write()`
     * operation.
     *
     * @throws {Error}
     * Thrown if the selected original stream does not provide a `write()`
     * operation.
     *
     * @since 1.0.0
     */
    #_writeEntry(entry: TerminalBufferEntry): boolean {
        const { isError, output, encoding, callback } = entry;
        const writer = this.#_originals[isError ? 'stderr' : 'stdout'];
        const stream = ZexiTerminalIO.streams[isError ? 'stderr' : 'stdout'];

        if (!writer.write) {
            throw new Error(
                `Invariant violation: Original ${isError ? 'stderr' : 'stdout'} stream does not provide a write operation.`
            );
        }

        const result = (() => {
            if (!callback && !encoding) {
                return writer.write.call(stream, output);
            }

            if (callback && !encoding) {
                return writer.write.call(stream, output, callback as any);
            }

            return writer.write.call(stream, output, encoding, callback);
        })();

        return result;
    }

    /**
     * Captures the original standard-stream operations and global console instance
     * associated with the currently configured terminal streams.
     *
     * Each available stream operation is retained as its original function reference
     * without modification. The captured operations can subsequently be invoked with
     * their respective streams as their `this` context, allowing Zexi to bypass its
     * interceptors while preserving the behavior of the original stream methods.
     *
     * Stream operations that are unavailable in the current environment are omitted,
     * allowing the terminal I/O interface to operate with non-TTY or otherwise limited
     * streams.
     *
     * The captured operations represent the un-intercepted state that Zexi restores
     * when its terminal interceptors are uninstalled.
     *
     * Capture is performed only once for the current stream configuration. Subsequent
     * invocations are ignored when the original operations have already been captured.
     *
     * @since 1.0.0
     */
    #_capture() {
        if (this.#_flags.captured) { return }

        const streams = ZexiTerminalIO.streams;
        const stdout: Partial<ProcessStdWriteStream> = {};
        const stderr: Partial<ProcessStdWriteStream> = {};

        const capture = (
            original: ProcessStdWriteStream,
            target: Partial<ProcessStdWriteStream>
        ): void => {
            if (original.write) { target.write = original.write; }
            if (original.cursorTo) { target.cursorTo = original.cursorTo; }
            if (original.clearLine) { target.clearLine = original.clearLine; }
            if (original.clearScreenDown) { target.clearScreenDown = original.clearScreenDown; }
            if (original.moveCursor) { target.moveCursor = original.moveCursor; }
        }

        capture(streams.stdout, stdout);
        capture(streams.stderr, stderr);

        this.#_originals = Object.seal({
            stdout: Object.freeze(stdout),
            stderr: Object.freeze(stderr),
            console: globalThis.console
        });

        this.#_flags.captured = true;
    }

    /**
     * Initializes the terminal I/O interface.
     *
     * The original process standard-stream operations and global console instance
     * are captured before Zexi installs its interceptors, ensuring Zexi retains
     * access to the un-intercepted stream operations and can later restore the
     * original process state.
     *
     * Interception is enabled immediately after the originals are captured so that
     * writes received while the terminal is initializing cannot bypass Zexi's
     * terminal pipeline.
     *
     * Until terminal initialization completes, intercepted writes are retained by
     * {@link queue} and flushed when {@link onReady} is invoked.
     *
     * @since 1.0.0
     */
    constructor() {
        this.#_capture();
        this.#_interception.enable();
    }

    /**
     * Provides the handler used to signal that terminal initialization has
     * completed.
     *
     * Invoking the handler flushes all intercepted writes that were received
     * before the terminal became ready and then marks the terminal as ready.
     *
     * @returns The terminal readiness handler.
     *
     * @since 1.0.0
     */
    get onReady() { return this.#_onReady; }

    /**
     * Indicates whether the terminal has completed initialization and flushed all
     * previously buffered writes.
     *
     * This value remains `false` while the terminal is initializing and throughout
     * the buffer-flushing phase. It becomes `true` only after the entire buffer
     * has been written to the original process streams.
     *
     * @returns `true` when the terminal is ready; otherwise, `false`.
     *
     * @since 1.0.0
     */
    get ready() { return this.#_flags.ready; }

    /**
     * Indicates whether Zexi's terminal interceptors are currently installed
     * on the process standard streams.
     *
     * This remains `true` after interception is disabled until {@link uninstall}
     * restores the original process stream methods.
     *
     * @returns `true` when the interceptors are installed; otherwise `false`.
     *
     * @since 1.0.0
     */
    get installed() { return this.#_flags.installed; }

    /**
     * Indicates whether Zexi is actively intercepting terminal operations.
     *
     * A value of `false` does not necessarily mean that the interceptors have
     * been removed. The interceptors may remain installed while transparently
     * forwarding operations to the original process stream methods.
     *
     * @returns `true` when interception is active; otherwise `false`.
     *
     * @since 1.0.0
     */
    get intercepting() { return this.#_flags.intercepting; }

    /**
     * Enables or disables active terminal interception.
     *
     * Setting this property to `true` enables interception and installs the
     * terminal interceptors when necessary.
     *
     * Setting this property to `false` disables active interception but leaves
     * the interceptors installed for transparent forwarding.
     *
     * A non-boolean value is rejected.
     *
     * @param value - Whether active terminal interception should be enabled.
     *
     * @throws TypeError if `value` is not a boolean.
     *
     * @since 1.0.0
     */
    set intercepting(value: boolean) {
        if (typeof value !== 'boolean') {
            throw new TypeError(`Expected \`intercepting\` to be a boolean, received \`${typeof value}\``);
        }

        if (value === true) {
            this.#_interception.enable();
        } else {
            this.#_interception.disable();
        }
    }

    /**
     * Replaces the terminal streams managed by Zexi and rebinds the terminal I/O
     * instance to their original stream operations.
     *
     * Any currently installed interceptors are first removed and the original
     * terminal streams are restored. The configured streams are then selectively
     * replaced with the supplied input, output, and error streams, after which
     * the original operations of all managed streams are captured for subsequent
     * interception and restoration.
     *
     * Any stream omitted from the supplied configuration remains unchanged.
     *
     * If terminal interception was active before the replacement, it is re-enabled
     * after the new streams have been bound. Otherwise, interception remains
     * disabled.
     *
     * This method must be used instead of directly replacing
     * {@link ZexiTerminalIO.streams}, as direct replacement bypasses the binding
     * lifecycle and may leave the captured original operations associated with the
     * previous streams.
     *
     * @param streams - The terminal streams to replace.
     * @param streams.output - The replacement stream for standard output.
     * @param streams.error - The replacement stream for standard error.
     * @param streams.input - The replacement stream for standard input.
     *
     * @since 1.0.0
     */
    replaceStreams(
        streams: {
            output?: unknown,
            error?: unknown,
            input?: unknown
        }
    ) {
        const wasIntercepting = this.intercepting;

        this.uninstall();

        if (streams.output) {
            ZexiTerminalIO.streams.stdout = streams.output as any;
        }

        if (streams.error) {
            ZexiTerminalIO.streams.stderr = streams.error as any;
        }

        if (streams.input) {
            ZexiTerminalIO.streams.stdin = streams.input as any;
        }

        this.#_flags.captured = false;
        this.#_capture();

        if (wasIntercepting) {
            this.intercepting = true;
        }
    }

    /**
     * Completely removes Zexi's terminal interception from the process.
     *
     * Active interception is disabled first, which also removes the signal
     * handlers registered for process termination.
     *
     * The installed interceptors are then removed and the original
     * `process.stdout` and `process.stderr` methods are restored.
     *
     * After this operation, the process standard streams are returned to the
     * state they had before Zexi installed its interceptors.
     *
     * @since 1.0.0
     */
    uninstall() {
        this.#_interception.disable();
        this.#_interception.uninstall();
    }

    /**
     * Queues a terminal write until the terminal becomes ready.
     *
     * When the terminal is already ready, the write is forwarded immediately to
     * {@link write}. Otherwise, the request is added to the internal buffer and
     * retained until {@link onReady} is invoked.
     *
     * Buffered requests are flushed in the order in which they were received.
     * The terminal remains not ready while the buffer is being flushed so that
     * writes received during the flush are also added to the buffer and preserved
     * in their correct order.
     *
     * @typeParam T - Whether the output is written to stderr.
     *
     * @param output - Data to write to the selected standard stream.
     * @param options - Optional stream selection, encoding, and completion
     * callback.
     *
     * @returns The result of the immediate write when the terminal is ready, or
     * `true` when the request has been accepted for deferred writing.
     *
     * @since 1.0.0
     */
    queue<T extends boolean>(
        output: string | Uint8Array,
        options?: {
            isError?: T
            callback?: (err?: Error | null) => void,
            encoding?: BufferEncoding,
        }
    ): boolean {
        if (this.ready) {
            return this.write(output, options);
        }

        const entry = {
            output,
            isError: options?.isError === true,
            callback: typeof options?.callback === 'function' ? options.callback : undefined,
            encoding: typeof options?.encoding === 'string' ? options.encoding : undefined
        };

        this.#_buffer.push(entry);
        return true;
    }

    /**
     * Writes directly to the original process standard stream.
     *
     * This method bypasses Zexi's installed interceptors and is therefore the
     * physical output path used by Zexi when it must write directly to the
     * terminal.
     *
     * The destination stream is selected using the `isError` option:
     *
     * - `false` writes to the original stdout stream
     * - `true` writes to the original stderr stream
     *
     * The remaining options follow the standard Node.js `write()` overloads for
     * string or byte output.
     *
     * This method is intentionally used by Zexi's interceptors and terminal
     * rendering code to prevent internally generated output from recursively
     * entering the interception pipeline.
     *
     * @typeParam T - Whether the output is written to stderr.
     *
     * @param output - Data to write to the selected standard stream.
     * @param options - Optional stream selection, encoding, and completion
     * callback.
     *
     * @returns The return value of the original standard-stream `write()`
     * operation.
     *
     * @since 1.0.0
     */
    write<T extends boolean>(
        output: string | Uint8Array,
        options?: {
            isError?: T
            callback?: (err?: Error | null) => void,
            encoding?: BufferEncoding,
        }
    ): WriteReturnType<T> {
        const entry = {
            output,
            isError: options?.isError === true,
            callback: typeof options?.callback === 'function' ? options.callback : undefined,
            encoding: typeof options?.encoding === 'string' ? options.encoding : undefined
        }

        return this.#_writeEntry(entry) as WriteReturnType<T>;
    }

    /**
     * Positions the terminal cursor at the specified coordinates.
     *
     * When only the horizontal coordinate is provided, the cursor is positioned
     * on that column of the current row.
     *
     * When both coordinates are provided, the cursor is positioned at the
     * specified column and row.
     *
     * The coordinates are converted to the corresponding ANSI cursor-positioning
     * sequence and written through the original stdout writer. This bypasses
     * Zexi's installed interceptors so that terminal control sequences generated
     * by Zexi do not re-enter the interception pipeline.
     *
     * @param x - Zero-based horizontal cursor position.
     * @param y - Optional zero-based vertical cursor position.
     * @param callback - Optional callback invoked after the sequence is written.
     *
     * @returns Whether the control sequence was accepted for writing.
     *
     * @since 1.0.0
     */
    cursorTo(x: number, y?: number, callback?: () => void): boolean;
    cursorTo(x: number, callback: () => void): boolean;
    cursorTo(x: number, y?: number | (() => void), callback?: () => void): boolean {
        const req: {
            x: number,
            y?: number,
            cb?: () => void
        } = { x };

        if (typeof y === 'number') {
            req.y = y;
        } else if (typeof y === 'function') {
            req.cb = y;
        }

        if (typeof callback === 'function') {
            req.cb = callback;
        }

        const sequence = req.y === undefined
            ? `\x1b[${req.x + 1}G`
            : `\x1b[${req.y + 1};${x + 1}H`;

        return this.write(sequence, { callback: req.cb });
    }

    /**
     * Clears the specified portion of the current terminal line.
     *
     * The direction follows the Node.js `clearLine()` convention:
     *
     * - `0` clears from the cursor to the end of the line
     * - `1` clears from the beginning of the line to the cursor
     * - `-1` clears the entire line
     *
     * The direction is translated to the corresponding ANSI erase-line sequence
     * and written through the original stdout writer. This bypasses Zexi's
     * installed interceptors so that terminal control sequences generated by
     * Zexi do not re-enter the interception pipeline.
     *
     * @param direction - Portion of the current line to clear.
     * @param callback - Optional callback invoked after the sequence is written.
     *
     * @returns Whether the control sequence was accepted for writing.
     *
     * @since 1.0.0
     */
    clearLine(direction: -1 | 0 | 1 = 0, callback?: () => void): boolean {
        const ansiDirection = direction === -1 ? 2 : direction;
        return this.write(`\x1b[${ansiDirection}K`, { callback });
    }

    /**
     * Clears the terminal from the current cursor position downward.
     *
     * The corresponding ANSI erase-in-display sequence is written through the
     * original stdout writer. This bypasses Zexi's installed interceptors so that
     * terminal control sequences generated by Zexi do not re-enter the
     * interception pipeline.
     *
     * @param callback - Optional callback invoked after the sequence is written.
     *
     * @returns Whether the control sequence was accepted for writing.
     *
     * @since 1.0.0
     */
    clearScreenDown(callback?: () => void): boolean {
        return this.write('\x1b[0J', { callback });
    }

    /**
     * Moves the terminal cursor relative to its current position.
     *
     * Horizontal and vertical movement are converted to the corresponding ANSI
     * cursor-movement sequences. Positive and negative values move the cursor in
     * opposite directions:
     *
     * - positive `dx` moves right
     * - negative `dx` moves left
     * - positive `dy` moves down
     * - negative `dy` moves up
     *
     * The generated sequences are written through the original stdout writer.
     * This bypasses Zexi's installed interceptors so that terminal control
     * sequences generated by Zexi do not re-enter the interception pipeline.
     *
     * @param dx - Number of columns to move horizontally.
     * @param dy - Number of rows to move vertically.
     * @param callback - Optional callback invoked after the sequence is written.
     *
     * @returns Whether the control sequence was accepted for writing.
     *
     * @since 1.0.0
     */
    moveCursor(dx: number, dy: number, callback?: () => void): boolean {
        let sequence = '';

        if (dy < 0) {
            sequence += `\x1b[${-dy}A`;
        } else if (dy > 0) {
            sequence += `\x1b[${dy}B`;
        }

        if (dx > 0) {
            sequence += `\x1b[${dx}C`;
        } else if (dx < 0) {
            sequence += `\x1b[${-dx}D`;
        }

        return this.write(sequence, { callback });
    }

    /**
     * Queries the terminal for its current cursor position.
     *
     * The query is delegated to the low-level cursor-position helper, which
     * communicates with the terminal using the ANSI Device Status Report
     * sequence.
     *
     * This method provides the terminal I/O boundary for cursor-position queries
     * performed by Zexi. The underlying input handling and ANSI response parsing
     * remain encapsulated by the helper.
     *
     * The returned coordinates are one-based and represent the cursor position
     * reported by the terminal.
     *
     * @returns Promise resolving to the current terminal cursor position.
     *
     * @throws Error if the cursor-position query cannot be completed.
     *
     * @since 1.0.0
     */
    queryCursorPosition(): Promise<CursorPosition> {
        return queryCursorPosition();
    }
}

/**
 * Shared Zexi terminal I/O controller.
 *
 * This singleton instance provides the terminal I/O boundary used throughout
 * Zexi. All physical terminal output and terminal control operations performed
 * by Zexi are routed through this instance.
 *
 * The shared instance ensures that all terminal components operate against the
 * same interception state, initialization buffer, original stream references,
 * and terminal output pipeline.
 *
 * @since 1.0.0
 */
const terminalIO = new ZexiTerminalIO();
export default terminalIO;