import type { EventEmitter } from '@nasriya/atomix/tools'
import type {
    SessionEventsMap,
    SessionReadyEventHandler,
    SessionReleaseEventHandler
} from "./types";

/**
 * Represents a single consumer's participation in the terminal STDIN
 * session manager.
 *
 * A `StdinSession` provides a controlled interface through which a consumer
 * can:
 *
 * - subscribe to session lifecycle events;
 * - receive normalized STDIN input while the session is active;
 * - indicate that it is ready to receive input;
 * - release STDIN when it has finished.
 *
 * A session does **not** directly control STDIN itself. In particular,
 * calling {@link ready} does not start STDIN capture, and calling
 * {@link release} does not directly stop it.
 *
 * Those operations are performed by the session manager. The session merely
 * notifies the manager of the consumer's intent.
 *
 * ### Session lifecycle
 *
 * A session normally progresses through the following lifecycle:
 *
 * ```
 * pending → ready → started → released
 * ```
 *
 * Calling {@link ready} requests the transition from `pending` to `ready`.
 * The session manager decides when the session actually becomes `started`.
 *
 * Once started, the session receives `input` events containing normalized
 * terminal keys.
 *
 * Calling {@link release} indicates that the consumer is finished. The
 * session manager then removes the session from its active or waiting
 * state and may activate another waiting session.
 *
 * A session can only be readied once and released once. Repeated calls to
 * either method are intentionally ignored.
 *
 * @internal
 * @since 1.0.0
 */
class StdinSession {
    /**
     * Event emitter shared with the session manager.
     *
     * The emitter carries both lifecycle events generated by the manager and
     * input events forwarded from STDIN.
     *
     * @internal
     */
    readonly #_events: EventEmitter<SessionEventsMap>;

    /**
     * Manager-owned callbacks used to notify the session manager when the
     * consumer changes the session's lifecycle state.
     *
     * These callbacks are deliberately kept separate from the public event
     * emitter:
     *
     * - `onReady` is invoked when the consumer calls {@link ready}.
     * - `onRelease` is invoked when the consumer calls {@link release}.
     *
     * Consumers cannot replace or invoke these callbacks directly.
     *
     * @internal
     */
    readonly #_systemEvents = {
        onReady: null as SessionReadyEventHandler | null,
        onRelease: null as SessionReleaseEventHandler | null,
    }

    /**
     * Internal lifecycle flags.
     *
     * `initialized` prevents the session manager from installing its internal
     * callbacks more than once.
     *
     * `onReadyCalled` ensures that {@link ready} is idempotent. Once a session
     * has declared itself ready, subsequent calls have no effect.
     *
     * `onReleaseCalled` ensures that {@link release} is idempotent. Once a
     * session has been released, subsequent calls have no effect.
     *
     * @internal
     */
    readonly #_flags = {
        initialized: false,
        onReadyCalled: false,
        onReleaseCalled: false
    }

    /**
     * Creates a STDIN session.
     *
     * The event emitter is supplied by the session manager rather than created
     * by the session itself. This allows the manager to retain control over
     * the session's lifecycle while exposing the session as a small consumer-
     * facing handle.
     *
     * @param eventsManager
     * The event emitter through which session lifecycle and input events are
     * communicated.
     *
     * @internal
     * @since 1.0.0
     */
    constructor(eventsManager: EventEmitter<SessionEventsMap>) {
        this.#_events = eventsManager;
    }

    /**
     * Registers an event handler for a session event.
     *
     * The most important event for consumers is `input`, which receives
     * normalized terminal keys while this session is active.
     *
     * Lifecycle events are also exposed so internal consumers can react when
     * the session becomes ready, starts, or is released.
     *
     * @example
     *
     * ```ts
     * session.on('input', key => {
     *     if (key.type === 'character') {
     *         console.log(key.value);
     *     }
     * });
     * ```
     *
     * @param event
     * The name of the event to subscribe to.
     *
     * @param handler
     * The callback to invoke when the event occurs.
     *
     * @internal
     * @since 1.0.0
     */
    on<E extends keyof SessionEventsMap>(
        event: E,
        handler: SessionEventsMap[E]
    ) {
        this.#_events.on<keyof SessionEventsMap>(event, handler);
    }

    /**
     * Registers an event handler that is automatically removed after the
     * first occurrence of the specified event.
     *
     * This is useful for lifecycle events such as `start` or `release` that
     * are expected to occur at most once during a session's lifetime.
     *
     * @example
     *
     * ```ts
     * session.once('start', () => {
     *     // The session has become active.
     * });
     * ```
     *
     * @param event
     * The name of the event to subscribe to.
     *
     * @param handler
     * The callback to invoke once when the event occurs.
     *
     * @internal
     * @since 1.0.0
     */
    once<E extends keyof SessionEventsMap>(
        event: E,
        handler: SessionEventsMap[E]
    ) {
        this.#_events.on<keyof SessionEventsMap>(event, handler, { once: true });
    }

    /**
     * Declares the session ready to receive STDIN input.
     *
     * This method does **not** immediately start STDIN capture.
     *
     * Instead, it notifies the session manager that the consumer has finished
     * setting up its session and is ready to receive input. The manager then
     * places the session into the appropriate queue and eventually starts it
     * when all preceding sessions have released STDIN.
     *
     * This distinction is important when multiple sessions are created
     * without awaiting each one:
     *
     * ```ts
     * const first = sessionManager.create();
     * const second = sessionManager.create();
     *
     * first.ready();
     * second.ready();
     * ```
     *
     * `second` does not start immediately. It waits until `first` releases
     * STDIN.
     *
     * Calling this method more than once has no effect.
     *
     * @internal
     * @since 1.0.0
     */
    ready() {
        if (this.#_flags.onReadyCalled) { return }

        this.#_flags.onReadyCalled = true;
        this.#_systemEvents.onReady?.();
    }

    /**
     * Releases the session's claim to STDIN.
     *
     * Calling this method indicates that the consumer has finished capturing
     * input and no longer needs to receive `input` events.
     *
     * The session manager performs the actual cleanup and, if another session
     * is waiting, may activate that session.
     *
     * Releasing a session does not directly stop STDIN. If another session is
     * already waiting in the manager's ready queue, STDIN remains active and
     * is transferred to that session.
     *
     * Calling this method more than once has no effect.
     *
     * @internal
     * @since 1.0.0
     */
    release() {
        if (this.#_flags.onReleaseCalled) { return }

        this.#_flags.onReleaseCalled = true;
        this.#_systemEvents.onRelease?.();
    }

    /**
     * Installs the internal callbacks used by the session manager.
     *
     * These callbacks form the private control channel between the session
     * and its manager:
     *
     * - `onReady` is invoked when the session calls {@link ready}.
     * - `onRelease` is invoked when the session calls {@link release}.
     *
     * This method is intentionally static so the internal callbacks cannot
     * become part of the session's normal public API.
     *
     * The callbacks may only be installed once. Attempting to initialize an
     * already initialized session indicates an internal lifecycle error and
     * therefore throws.
     *
     * @param session
     * The session whose manager callbacks should be installed.
     *
     * @param events
     * The manager-owned lifecycle callbacks.
     *
     * @throws {Error}
     * Thrown when the session has already been initialized with manager
     * callbacks.
     *
     * @internal
     * @since 1.0.0
     */
    static setEvents(
        session: StdinSession,
        events: {
            onReady: SessionReadyEventHandler;
            onRelease: SessionReleaseEventHandler;
        }
    ) {
        if (session.#_flags.initialized) {
            throw new Error('Invariant violation: session events already set.');
        }

        session.#_systemEvents.onReady = events.onReady;
        session.#_systemEvents.onRelease = events.onRelease;
        session.#_flags.initialized = true;
    }
}

export default StdinSession;